parameters:
#    dv_installer.example.class: DV\Bundle\InstallerBundle\Example

services:
#    dv_installer.example:
#        class: %dv_installer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
